name: Cypress Tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Format check
        run: npm run format

      - name: Start app locally
        run: |
          nohup npm run start

      - name: Start tests
        run: |
          cd e2e
          npm i
          npm run test:ci
