name: Cypress Tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start services
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Install
        run: npm ci

      - name: Format check
        run: npm run format

      - name: Start app locally
        run: |
          npm start $
          sleep 10

      - name: Start tests
        run: |
          cd e2e
          npm i
          npm run test:ci

      - name: Stop app
        run: kill $(jobs -p) || true
