name: Cypress Tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start services
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Install
        run: npm ci

      - name: Format check
        run: npm run format

      - name: Build app
        run: npm run build

      - name: Start app in the background
        run: npm run start:background

      - name: Start tests
        run: |
          cd e2e
          npm i
          npm run test:ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Stop app
        run: npm run stop:background
